# Classification multi-étiquette

In [1]:
# Chargement des modules necessaires

import os

import random

import numpy as np

import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Convolution2D, MaxPooling2D, ZeroPadding2D
from tensorflow.keras import optimizers
from tensorflow.keras.preprocessing.image import load_img,img_to_array

In [2]:
# On declare les chemins vers les donnees :

Image = 'Data'
        
train_data_dir = 'Data/TRAIN'
validation_data_dir = 'Data/VALIDATION'
test_data_dir = 'Data/TEST'

# Dimmension et path :
img_width, img_height = 224, 224

#ImageTRAINCOVID = os.listdir(Image + '/TRAIN/COVID')
ImageTRAINATELECTASIS = os.listdir(Image + '/TRAIN/ATELECTASIS')
ImageTRAINNORMAL = os.listdir(Image + '/TRAIN/NORMAL')
ImageTRAINEFFUSION = os.listdir(Image + '/TRAIN/EFFUSION')
ImageTRAINEMPHYSEMA = os.listdir(Image + '/TRAIN/EMPHYSEMA')
ImageTRAININFILTRATION = os.listdir(Image + '/TRAIN/INFILTRATION')
ImageTRAINPNEUMONIE = os.listdir(Image + '/TRAIN/PNEUMONIE')

#ImageVALIDATIONCOVID = os.listdir(Image + '/VALIDATION/COVID')
ImageVALIDATIONATELECTASIS = os.listdir(Image + '/VALIDATION/ATELECTASIS')
ImageVALIDATIONNORMAL = os.listdir(Image + '/VALIDATION/NORMAL')
ImageVALIDATIONEFFUSION = os.listdir(Image + '/VALIDATION/EFFUSION')
ImageVALIDATIONEMPHYSEMA = os.listdir(Image + '/VALIDATION/EMPHYSEMA')
ImageVALIDATIONINFILTRATION = os.listdir(Image + '/VALIDATION/INFILTRATION')
ImageVALIDATIONPNEUMONIE = os.listdir(Image + '/VALIDATION/PNEUMONIE')

#ImageTESTCOVID = os.listdir(Image + '/TEST/COVID')
ImageTESTATELECTASIS = os.listdir(Image + '/TEST/ATELECTASIS')
ImageTESTNORMAL = os.listdir(Image + '/TEST/NORMAL')
ImageTESTEFFUSION = os.listdir(Image + '/TEST/EFFUSION')
ImageTESTEMPHYSEMA = os.listdir(Image + '/TEST/EMPHYSEMA')
ImageTESTINFILTRATION = os.listdir(Image + '/TEST/INFILTRATION')
ImageTESTPNEUMONIE = os.listdir(Image + '/TEST/PNEUMONIE')

#print('Il y a ' + str(len(ImageTRAINCOVID)) + ' images d\'entrainement de patient covid.') 
print('Il y a ' + str(len(ImageTRAINNORMAL)) + ' images d\'entrainement de patient sain.') 
print('Il y a ' + str(len(ImageTRAINATELECTASIS)) + ' images d\'entrainement de patient atelectasis.') 
print('Il y a ' + str(len(ImageTRAINEFFUSION)) + ' images d\'entrainement de patient effusion.') 
print('Il y a ' + str(len(ImageTRAINEMPHYSEMA)) + ' images d\'entrainement de patient emphyseme.') 
print('Il y a ' + str(len(ImageTRAININFILTRATION)) + ' images d\'entrainement de patient infltration.')
print('Il y a ' + str(len(ImageTRAINPNEUMONIE)) + ' images d\'entrainement de patient pneumonie.')

#print('Il y a ' + str(len(ImageVALIDATIONCOVID)) + ' images de validation de patient covid.') 
print('Il y a ' + str(len(ImageVALIDATIONNORMAL)) + ' images de validation de patient non-covid.') 
print('Il y a ' + str(len(ImageVALIDATIONATELECTASIS)) + ' images de validation de patient atelectasis.') 
print('Il y a ' + str(len(ImageVALIDATIONEFFUSION)) + ' images de validation de patient effusion.') 
print('Il y a ' + str(len(ImageVALIDATIONEMPHYSEMA)) + ' images de validation de patient emphyseme.') 
print('Il y a ' + str(len(ImageVALIDATIONINFILTRATION)) + ' images de validation de patient infltration.')
print('Il y a ' + str(len(ImageVALIDATIONPNEUMONIE)) + ' images de validation de patient pneumonie.')

#print('Il y a ' + str(len(ImageTESTCOVID)) + ' images test de patient covid.') 
print('Il y a ' + str(len(ImageTESTNORMAL)) + ' images test de patient non-covid.')
print('Il y a ' + str(len(ImageTESTATELECTASIS)) + ' images test de patient atelectasis.') 
print('Il y a ' + str(len(ImageTESTEFFUSION)) + ' images test de patient effusion.') 
print('Il y a ' + str(len(ImageTESTEMPHYSEMA)) + ' images test de patient emphyseme.') 
print('Il y a ' + str(len(ImageTESTINFILTRATION)) + ' images test de patient infltration.')
print('Il y a ' + str(len(ImageTESTPNEUMONIE)) + ' images test de patient pneumonie.')

Il y a 690 images d'entrainement de patient sain.
Il y a 304 images d'entrainement de patient atelectasis.
Il y a 378 images d'entrainement de patient effusion.
Il y a 580 images d'entrainement de patient emphyseme.
Il y a 580 images d'entrainement de patient infltration.
Il y a 1000 images d'entrainement de patient pneumonie.
Il y a 230 images de validation de patient non-covid.
Il y a 102 images de validation de patient atelectasis.
Il y a 133 images de validation de patient effusion.
Il y a 193 images de validation de patient emphyseme.
Il y a 193 images de validation de patient infltration.
Il y a 333 images de validation de patient pneumonie.
Il y a 230 images test de patient non-covid.
Il y a 102 images test de patient atelectasis.
Il y a 133 images test de patient effusion.
Il y a 193 images test de patient emphyseme.
Il y a 387 images test de patient infltration.
Il y a 333 images test de patient pneumonie.


In [3]:
# Preprocessing :

# On rescale les images :

datagen = ImageDataGenerator(rescale=1./255)

# On definit la batch size :

batch_size = 32 

# On prepare les tableaux de donnees depuis les images :

train_generator = datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size)

validation_generator = datagen.flow_from_directory(
        validation_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size)

test_generator = datagen.flow_from_directory(
        test_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size)

Found 3532 images belonging to 6 classes.
Found 1184 images belonging to 6 classes.
Found 1378 images belonging to 6 classes.


In [4]:
# On definit l'architecture du model :

model = Sequential()
model.add(Convolution2D(32, (3, 3), input_shape=(img_width, img_height,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Convolution2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Convolution2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(6))
model.add(Activation('softmax'))

# On compile le modeles :

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# On affiche le model :

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 222, 222, 32)      896       
_________________________________________________________________
activation (Activation)      (None, 222, 222, 32)      0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 111, 111, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 109, 109, 32)      9248      
_________________________________________________________________
activation_1 (Activation)    (None, 109, 109, 32)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 54, 54, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 52, 52, 64)        1

In [5]:
# On definit les paramétres pour l'entrainement :

epochs = 10
train_samples = 3532
validation_samples = 1184
test_samples = 1378

In [6]:
historique = model.fit_generator(
        train_generator,
        steps_per_epoch=train_samples // batch_size,
        epochs=epochs,
        validation_data=validation_generator,
        validation_steps=validation_samples// batch_size)

Epoch 1/10
110/110 [==============================] - 941s 9s/step - loss: 1.3502 - accuracy: 0.4457 - val_loss: 1.0889 - val_accuracy: 0.5397
Epoch 2/10
110/110 [==============================] - 1005s 9s/step - loss: 0.9856 - accuracy: 0.5700 - val_loss: 0.8825 - val_accuracy: 0.5819
Epoch 3/10
110/110 [==============================] - 1344s 12s/step - loss: 0.9148 - accuracy: 0.5920 - val_loss: 0.8662 - val_accuracy: 0.5929
Epoch 4/10
110/110 [==============================] - 1454s 13s/step - loss: 0.8935 - accuracy: 0.5883 - val_loss: 0.8366 - val_accuracy: 0.5988
Epoch 5/10
110/110 [==============================] - 883s 8s/step - loss: 0.8352 - accuracy: 0.6023 - val_loss: 0.8165 - val_accuracy: 0.6030
Epoch 6/10
110/110 [==============================] - 900s 8s/step - loss: 0.8184 - accuracy: 0.6103 - val_loss: 0.8640 - val_accuracy: 0.5921
Epoch 7/10
110/110 [==============================] - 1048s 10s/step - loss: 0.8035 - accuracy: 0.6111 - val_loss: 0.8466 - val_accuracy:

In [7]:
# Enregistrement des donnees

np.save('models/historique_scratch_224_224_10G_Baudouin.npy',historique.history)

model.save('models/scratchFull_10G_224_224')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: models/scratchFull_10G_224_224/assets


In [8]:
# Evaluation des modeles

resultValidation = model.evaluate_generator(validation_generator, validation_samples)
resultTest = model.evaluate_generator(test_generator, test_samples)


print(resultValidation)
print(resultTest)

[0.8649289111380238, 0.6021959]
[1.2720320892402408, 0.4518371]


In [22]:
def testImage(path):
    img = load_img(path, target_size=(224,224))
    img = img_to_array(img)
    img = img.reshape((1, img.shape[0], img.shape[1], img.shape[2]))
    y = model.predict(img)
    return y

In [50]:
for i in range(10):
    result = testImage(Image+"/TEST/ATELECTASIS/"+ImageTESTATELECTASIS[i])[0]
    item = max(result)
    itemindex = np.where(result==item)
    print(itemindex)
    
print('End ---- ')

for i in range(10):
    result = testImage(Image+"/TEST/EFFUSION/"+ImageTESTEFFUSION[i])[0]
    item = max(result)
    itemindex = np.where(result==item)
    print(itemindex)
    
print('End ---- ')

for i in range(10):
    result = testImage(Image+"/TEST/EMPHYSEMA/"+ImageTESTEMPHYSEMA[i])[0]
    item = max(result)
    itemindex = np.where(result==item)
    print(itemindex)
    
print('End ---- ')

for i in range(10):
    result = testImage(Image+"/TEST/PNEUMONIE/"+ImageTESTPNEUMONIE[i])[0]
    item = max(result)
    itemindex = np.where(result==item)
    print(itemindex)
    
print('End ---- ')

(array([3]),)
(array([3]),)
(array([2]),)
(array([3]),)
(array([3]),)
(array([3]),)
(array([3]),)
(array([2]),)
(array([2]),)
(array([3]),)
End ---- 
(array([2]),)
(array([3]),)
(array([3]),)
(array([3]),)
(array([2]),)
(array([3]),)
(array([4]),)
(array([5]),)
(array([3]),)
(array([3]),)
End ---- 
(array([0]),)
(array([3]),)
(array([2]),)
(array([5]),)
(array([2]),)
(array([3]),)
(array([3]),)
(array([3]),)
(array([3]),)
(array([2]),)
End ---- 
(array([5]),)
(array([5]),)
(array([5]),)
(array([5]),)
(array([5]),)
(array([5]),)
(array([5]),)
(array([5]),)
(array([5]),)
(array([5]),)
End ---- 


In [49]:
resultTotal = 0

for i in range(230):
    result = testImage(Image+"/TEST/NORMAL/"+ImageTESTNORMAL[i])[0]
    item = max(result)
    itemindex = np.where(result==item)
    if itemindex[0][0] == 4:
        resultTotal = resultTotal + 1
    
print('End ---- ')
print(resultTotal)

End ---- 
126


In [47]:
resultTotal = 0

for i in range(333):
    result = testImage(Image+"/TEST/PNEUMONIE/"+ImageTESTPNEUMONIE[i])[0]
    item = max(result)
    itemindex = np.where(result==item)
    if itemindex[0][0] == 5:
        resultTotal = resultTotal + 1
    
print('End ---- ')
print(resultTotal)

End ---- 
307
